baseURL = "https://blog.edfloreshz.dev"
languageCode = "en"
title = "edfloreshz"
theme = "monochrome"
defaultContentLanguage = "en"
enableEmoji = true
paginate = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
