baseURL: https://blog.edfloreshz.dev
languageCode: en-us
paginate: 5
title: Devloop

theme: "PaperMod"

menu:
  main:
    - identifier: articles
      name: Articles
      url: /articles/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

params:
  profileMode:
    enabled: true
    title: "Devloop" # optional default will be site title
    subtitle: "A blog about technology and programming 🦀"
    imageUrl: "images/logo/light.svg" # optional
    darkImageUrl: "images/logo/dark.svg" # optional
    imageTitle: "Logo" # optional
    imageWidth: 250 # custom size
    imageHeight: 250 # custom size
    buttons:
      - name: Articles
        url: "articles"

  ShowPostNavLinks: true
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  disableSpecial1stPost: false
  comments: true
  hidemeta: false
  showtoc: true
  tocopen: false

  assets:
    favicon: "images/favicon/favicon.png"
    favicon16x16: "images/favicon/favicon.png"
    favicon32x32: "images/favicon/favicon.png"
    apple_touch_icon: "images/favicon/favicon.png"
    safari_pinned_tab: "images/favicon/favicon.png"

  params:
    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: twitter
      url: "https://twitter.com/edfloreshz"
    - name: telegram
      url: "https://t.me/edfloreshz"
    - name: github
      url: "https://github.com/edfloreshz"
    - name: email
      url: "mailto:edfloreshz@gmail.com"

outputs:
  home:
    - HTML
    - RSS
    - JSON
