baseURL = "https://edfloreshz.dev"
languageCode = 'es-MX'
title = 'Eduardo Flores'
theme = "typo"

[taxonomies]
tag = 'tags'

[params]
homeIntroTitle = ''
homeIntroContent = 'Ingeniero de Software en México'

faviconPath = 'favicon'
theme = 'auto'
colorPalette = 'default'
hideHeader = false

showFooter = true
footerContent = "© 2025 Eduardo Flores"

# Collection to display on home
homeCollectionTitle = ''
homeCollection = 'entradas'

# Lists parameters
paginationSize = 1000
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false

[[params.menu]]
name = "inicio"
url = "/"

[[params.menu]]
name = "entradas"
url = "/entradas"

[[params.menu]]
name = "marca"
url = "https://brand.edfloreshz.dev"

[[params.menu]]
name = "ai"
url = "/ai"

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/edfloreshz/"

[[params.social]]
name = "mastodon"
url = "https://hachyderm.io/@edfloreshz"

[[params.social]]
name = "github"
url = "https://github.com/edfloreshz"

[[params.social]]
name = "twitch"
url = "https://www.twitch.tv/edfloreshz/about"

[[params.social]]
name = "matrix"
url = "https://matrix.to/#/@edfloreshz:matrix.org"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "edfloreshz/edfloreshz.dev"
repoid = "340447979"
category = "Announcements"
categoryid = "33718616"
mapping = "pathname"
theme = "preferred_color_scheme"
